apiVersion: v1
kind: Service
metadata:
  labels:
    app: message-server
  name: message-server
  namespace: message
spec:
  type: LoadBalancer
  ports:
  - name: "message-server"
    port: 8091
    targetPort: 8091
  selector:
    app: message-server
  
